[package]
name = "common"
version = "0.1.0"
edition = "2024"

[lib]
name = "common"
path = "src/lib.rs"

[dependencies]
axum = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
utoipa = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
serde_with = "3.16.1"
tracing = { workspace = true }
thiserror = { workspace = true }
sqlx = { workspace = true }
validator = { workspace = true, features = ["derive"] }
redis = { version = "1.0.2" }
deadpool-redis = "0.22.1" # 连接池
uuid = { version = "1.19.0", features = ["v4"] }
