[package]
name = "common"
version = "0.1.0"
edition = "2024"

[lib]
name = "common"
path = "src/lib.rs"

[dependencies]
axum = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
utoipa = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
