syntax = "proto3";

package common;

// 枚举类型
enum Status{
  UNKNOWN=0;
  SUCCESS=1;
  FAILED = 2;
  PENDING = 3;
}
// 定义公共消息
message CommonResponse {
  bool success = 1;
  int32 code = 2;
  string message = 3;
  Status status = 4;
}

message PageRequest{
  int32 page = 1;
  int32 page_size = 2;
  string sort_by = 3;
  bool descending = 4;
}

message PageResponse {
  int32 page = 1;
  int32 page_size = 2;
  int32 total = 3;
  int32 total_pages = 4;
}

// 时间范围
message TimeRange {
  int64 start_time = 1;
  int64 end_time = 2;
}
