[package]
name = "proto"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[lib]
name = "proto" # 明确指定库名
path = "src/lib.rs" # 明确指定库路径

[dependencies]
prost = { workspace = true }
prost-types = { workspace = true }
tonic = { workspace = true }
tonic-prost = { workspace = true }

# 构建依赖
[build-dependencies]
tonic-prost-build = "0.14.1"

[features]
default = []
server = []
client = []